### ISSUE TITLE
Invisible mouse cursor on spectator hud and commandmenu

### ISSUE THREAD

**Issue by ddagger1** [tmp64/BugfixedHL#28]
> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)
> 

> ] about
> Bugfixed and improved Half-Life client
> Version: 1.5.0+master.e293fe0
> Build options: VGUI2 support    game build 4554    auto-updater    
> Github: https://github.com/tmp64/BugfixedHL
> Discussion forum: http://aghl.ru/forum/viewtopic.php?f=36&t=686

**Comment by tmp64** [comment]
This happens because Spectator UI and Command Menu are VGUI1 panels. When VGUI2 is enabled on the client, it takes over mouse control from VGUI1, so it doesn't know that mouse cursor should be visible.

The only way I found to fix it is to rewrite these panels with VGUI2 which I'm working on in a separate repository. Until it's released, you'll have to navigate using the keyboard.

**Comment by ddagger1** [comment]
Hope you can fix this, it's kinda annoying using the keyboard for it. Esp in the Spectator one,
